## File Manipulation

In [12]:
libert_dir = "/data/home/ayalklei/nlp-architect/nlp_architect/models/libert"
domains = ["restaurants", "laptops", "device"]
import sys, os, json, glob, csv 


In [18]:
path = f"{libert_dir}/logs/Wed_Dec_16_11:18:36bert-amtl-all/dm"
counter=0
for dirn in os.listdir(path):
    if "_to_" in dirn:
        for subd in os.listdir(os.path.join(path, dirn)):
            for ssubd in os.listdir(os.path.join(path, dirn, subd)):
                if "libert_baseline" in ssubd:
                    counter += 1
                    os.rename(os.path.join(path, dirn, subd, ssubd), os.path.join(path, dirn, subd, ssubd.replace("libert_baseline", "bert_baseline")))

print(f"Made {counter} replacements.")

Made 108 replacements.


## Tensor operations

In [19]:
import torch
from torch import tensor as tn

In [50]:
x = torch.randint(4, (2,3,4))
y = torch.randint(2, (3,4))
z = torch.randint(3, (4,))
x, y, z

(tensor([[[2, 3, 2, 2],
          [1, 3, 0, 2],
          [1, 1, 0, 3]],
 
         [[1, 1, 1, 1],
          [3, 1, 1, 0],
          [3, 3, 1, 2]]]),
 tensor([[1, 1, 0, 1],
         [0, 1, 1, 0],
         [0, 1, 0, 0]]),
 tensor([1, 1, 1, 2]))

In [57]:
y.nonzero(as_tuple=False)

tensor([[0, 0],
        [0, 1],
        [0, 3],
        [1, 1],
        [1, 2],
        [2, 1]])